/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controller.CopiarFichaController;
import DAO.CopiarFichaDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author vinic
 */
public class CopiarFicha extends javax.swing.JInternalFrame {

    CopiarFichaController controller = new CopiarFichaController(this);

    /**
     * Creates new form Ficha
     */
    public CopiarFicha() {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Oculta botão
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0)); //Oculta as bordas do internalFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4_fundoAzul = new javax.swing.JPanel();
        copiarFicha_botao = new javax.swing.JPanel();
        copiarFicha_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_CodigoSerCopiado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_CodigoReceberCopia = new javax.swing.JTextField();

        setBorder(null);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(640, 520));
        setVisible(true);

        jPanel4_fundoAzul.setBackground(new java.awt.Color(36, 46, 68));

        copiarFicha_botao.setBackground(new java.awt.Color(89, 199, 198));

        copiarFicha_txt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        copiarFicha_txt.setForeground(new java.awt.Color(255, 255, 255));
        copiarFicha_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copiarFicha_txt.setText("Copiar Ficha");
        copiarFicha_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        copiarFicha_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copiarFicha_txtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copiarFicha_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copiarFicha_txtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout copiarFicha_botaoLayout = new javax.swing.GroupLayout(copiarFicha_botao);
        copiarFicha_botao.setLayout(copiarFicha_botaoLayout);
        copiarFicha_botaoLayout.setHorizontalGroup(
            copiarFicha_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(copiarFicha_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        copiarFicha_botaoLayout.setVerticalGroup(
            copiarFicha_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(copiarFicha_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código do produto à ser copiado");

        jTextField_CodigoSerCopiado.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextField_CodigoSerCopiado.setPreferredSize(new java.awt.Dimension(15, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Código do produto à receber a cópia");

        jTextField_CodigoReceberCopia.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextField_CodigoReceberCopia.setPreferredSize(new java.awt.Dimension(15, 25));

        javax.swing.GroupLayout jPanel4_fundoAzulLayout = new javax.swing.GroupLayout(jPanel4_fundoAzul);
        jPanel4_fundoAzul.setLayout(jPanel4_fundoAzulLayout);
        jPanel4_fundoAzulLayout.setHorizontalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_fundoAzulLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_CodigoReceberCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_CodigoSerCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(copiarFicha_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        jPanel4_fundoAzulLayout.setVerticalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_fundoAzulLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_CodigoSerCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_CodigoReceberCopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(copiarFicha_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copiarFicha_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copiarFicha_txtMouseClicked
        try {
            controller.copiarFicha();
        } catch (ClassNotFoundException ex) {
            System.err.println("Erro: " + ex);
        } catch (SQLException ex) {
            Logger.getLogger(CopiarFicha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_copiarFicha_txtMouseClicked

    private void copiarFicha_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copiarFicha_txtMouseEntered
        copiarFicha_txt.setForeground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_copiarFicha_txtMouseEntered

    private void copiarFicha_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copiarFicha_txtMouseExited
        copiarFicha_txt.setForeground(Color.white);
    }//GEN-LAST:event_copiarFicha_txtMouseExited

    public JTextField getjTextField_CodigoReceberCopia() {
        return jTextField_CodigoReceberCopia;
    }

    public void setjTextField_CodigoReceberCopia(JTextField jTextField_CodigoReceberCopia) {
        this.jTextField_CodigoReceberCopia = jTextField_CodigoReceberCopia;
    }

    public JTextField getjTextField_CodigoSerCopiado() {
        return jTextField_CodigoSerCopiado;
    }

    public void setjTextField_CodigoSerCopiado(JTextField jTextField_CodigoSerCopiado) {
        this.jTextField_CodigoSerCopiado = jTextField_CodigoSerCopiado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel copiarFicha_botao;
    private javax.swing.JLabel copiarFicha_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4_fundoAzul;
    private javax.swing.JTextField jTextField_CodigoReceberCopia;
    private javax.swing.JTextField jTextField_CodigoSerCopiado;
    // End of variables declaration//GEN-END:variables
}
