/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controller.GerarFichaController;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author vinic
 */
public class GerarFicha extends javax.swing.JInternalFrame {

    GerarFichaController controller = new GerarFichaController(this);

    //GerarFichaDAO dao = new GerarFichaDAO(this);
    /**
     * Creates new form Teste
     */
    public GerarFicha() {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Oculta botão
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0)); //Oculta as bordas do internalFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4_fundoAzul = new javax.swing.JPanel();
        jTextField_CodigoGerarFicha = new javax.swing.JTextField();
        gerarFicha_botao = new javax.swing.JPanel();
        gerarFicha_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 520));

        jPanel4_fundoAzul.setBackground(new java.awt.Color(36, 46, 68));

        jTextField_CodigoGerarFicha.setMinimumSize(new java.awt.Dimension(10, 20));
        jTextField_CodigoGerarFicha.setPreferredSize(new java.awt.Dimension(15, 25));

        gerarFicha_botao.setBackground(new java.awt.Color(89, 199, 198));

        gerarFicha_txt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        gerarFicha_txt.setForeground(new java.awt.Color(255, 255, 255));
        gerarFicha_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gerarFicha_txt.setText("Gerar Ficha Técnica");
        gerarFicha_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerarFicha_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerarFicha_txtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gerarFicha_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gerarFicha_txtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout gerarFicha_botaoLayout = new javax.swing.GroupLayout(gerarFicha_botao);
        gerarFicha_botao.setLayout(gerarFicha_botaoLayout);
        gerarFicha_botaoLayout.setHorizontalGroup(
            gerarFicha_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarFicha_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        gerarFicha_botaoLayout.setVerticalGroup(
            gerarFicha_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gerarFicha_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código");

        javax.swing.GroupLayout jPanel4_fundoAzulLayout = new javax.swing.GroupLayout(jPanel4_fundoAzul);
        jPanel4_fundoAzul.setLayout(jPanel4_fundoAzulLayout);
        jPanel4_fundoAzulLayout.setHorizontalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_fundoAzulLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CodigoGerarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerarFicha_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel4_fundoAzulLayout.setVerticalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_fundoAzulLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_CodigoGerarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gerarFicha_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarFicha_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerarFicha_txtMouseClicked
        try {
            controller.executar();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
            Logger.getLogger(GerarFicha.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
            Logger.getLogger(GerarFicha.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
            Logger.getLogger(GerarFicha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gerarFicha_txtMouseClicked

    private void gerarFicha_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerarFicha_txtMouseEntered
        gerarFicha_txt.setForeground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_gerarFicha_txtMouseEntered

    private void gerarFicha_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerarFicha_txtMouseExited
        gerarFicha_txt.setForeground(Color.white);
    }//GEN-LAST:event_gerarFicha_txtMouseExited

    public JTextField getjTextField_CodigoGerarFicha() {
        return jTextField_CodigoGerarFicha;
    }

    public void setjTextField_CodigoGerarFicha(JTextField jTextField_CodigoGerarFicha) {
        this.jTextField_CodigoGerarFicha = jTextField_CodigoGerarFicha;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gerarFicha_botao;
    private javax.swing.JLabel gerarFicha_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4_fundoAzul;
    private javax.swing.JTextField jTextField_CodigoGerarFicha;
    // End of variables declaration//GEN-END:variables
}
