/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author vinic
 */
public class Inicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ficha
     */
    public Inicio() {
        initComponents();

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Oculta botão do internalFrame
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0)); //Oculta as bordas do internalFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4_fundoAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_NomeUsuario = new javax.swing.JLabel();

        setBorder(null);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(640, 520));
        setVisible(true);

        jPanel4_fundoAzul.setBackground(new java.awt.Color(36, 46, 68));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa_inicio.png"))); // NOI18N

        jLabel_NomeUsuario.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel_NomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NomeUsuario.setText("Bem Vindo!");

        javax.swing.GroupLayout jPanel4_fundoAzulLayout = new javax.swing.GroupLayout(jPanel4_fundoAzul);
        jPanel4_fundoAzul.setLayout(jPanel4_fundoAzulLayout);
        jPanel4_fundoAzulLayout.setHorizontalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_fundoAzulLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel_NomeUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4_fundoAzulLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
        );
        jPanel4_fundoAzulLayout.setVerticalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_fundoAzulLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NomeUsuario)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4_fundoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_NomeUsuario;
    private javax.swing.JPanel jPanel4_fundoAzul;
    // End of variables declaration//GEN-END:variables
}
