/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controller.LoginController;
import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author vinic
 */
public class Login extends javax.swing.JFrame {

    private LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);//Abre JFrame no meio da página
        controller = new LoginController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        fichaTecnica = new javax.swing.JLabel();
        fichaTecnica1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        entre = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        preencherUsuario = new javax.swing.JTextField();
        usuario1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        preencherSenha = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        entrar_botao = new javax.swing.JPanel();
        entrar_txt = new javax.swing.JLabel();
        naoTemConta = new javax.swing.JLabel();
        cadastre = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(89, 199, 198));

        fichaTecnica.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        fichaTecnica.setForeground(new java.awt.Color(255, 255, 255));
        fichaTecnica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaTecnica.setText("Gerador");

        fichaTecnica1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        fichaTecnica1.setForeground(new java.awt.Color(255, 255, 255));
        fichaTecnica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaTecnica1.setText("Ficha Técnica");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lista.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fichaTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fichaTecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(fichaTecnica1)
                .addGap(6, 6, 6)
                .addComponent(fichaTecnica)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(130, 130, 130))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 520));

        jPanel4.setBackground(new java.awt.Color(36, 46, 68));

        entre.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        entre.setForeground(new java.awt.Color(255, 255, 255));
        entre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entre.setText("Entre");

        usuario.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("USUÁRIO");

        preencherUsuario.setBackground(new java.awt.Color(36, 46, 68));
        preencherUsuario.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        preencherUsuario.setForeground(new java.awt.Color(255, 255, 255));
        preencherUsuario.setBorder(null);

        usuario1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        usuario1.setForeground(new java.awt.Color(255, 255, 255));
        usuario1.setText("SENHA");

        preencherSenha.setBackground(new java.awt.Color(36, 46, 68));
        preencherSenha.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        preencherSenha.setForeground(new java.awt.Color(255, 255, 255));
        preencherSenha.setBorder(null);
        preencherSenha.setPreferredSize(new java.awt.Dimension(111, 21));

        entrar_botao.setBackground(new java.awt.Color(89, 199, 198));

        entrar_txt.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        entrar_txt.setForeground(new java.awt.Color(255, 255, 255));
        entrar_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrar_txt.setText("Entrar");
        entrar_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrar_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrar_txtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrar_txtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrar_txtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout entrar_botaoLayout = new javax.swing.GroupLayout(entrar_botao);
        entrar_botao.setLayout(entrar_botaoLayout);
        entrar_botaoLayout.setHorizontalGroup(
            entrar_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        entrar_botaoLayout.setVerticalGroup(
            entrar_botaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        naoTemConta.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        naoTemConta.setForeground(new java.awt.Color(255, 255, 255));
        naoTemConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naoTemConta.setText("Não possui conta?");

        cadastre.setFont(new java.awt.Font("Century Gothic", 2, 16)); // NOI18N
        cadastre.setForeground(new java.awt.Color(255, 255, 255));
        cadastre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastre.setText("Cadastre-se");
        cadastre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastreMouseExited(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        x.setForeground(new java.awt.Color(89, 199, 198));
        x.setText("X");
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                xAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        x.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                xMouseMoved(evt);
            }
        });
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/java.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(entre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 117, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                        .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(preencherUsuario)
                                        .addComponent(preencherSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(entrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(naoTemConta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(cadastre)))))
                                .addGap(107, 107, 107))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(x)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(246, 246, 246))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(x)
                .addGap(17, 17, 17)
                .addComponent(entre)
                .addGap(44, 44, 44)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preencherUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preencherSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(naoTemConta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(entrar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 570, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_xAncestorAdded
    }//GEN-LAST:event_xAncestorAdded

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        dispose();
    }//GEN-LAST:event_xMouseClicked

    private void xMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseMoved
    }//GEN-LAST:event_xMouseMoved

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        x.setForeground(Color.red); //Ao passar mouse pelo X deixa vermelho
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        x.setForeground(new java.awt.Color(89, 199, 198)); //Volta a cor padrão do X ao tirar o mouse
    }//GEN-LAST:event_xMouseExited

    private void cadastreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastreMouseClicked
        new Cadastro().setVisible(true);
    }//GEN-LAST:event_cadastreMouseClicked

    private void cadastreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastreMouseEntered
        cadastre.setForeground(new java.awt.Color(89, 199, 198));
    }//GEN-LAST:event_cadastreMouseEntered

    private void cadastreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastreMouseExited
        cadastre.setForeground(Color.white);
    }//GEN-LAST:event_cadastreMouseExited

    private void entrar_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_txtMouseClicked
        try {
            controller.autenticar();
        } catch (ClassNotFoundException | SQLException ex) {
            System.err.println("Erro: " + ex);
        }
    }//GEN-LAST:event_entrar_txtMouseClicked

    private void entrar_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_txtMouseEntered
        entrar_txt.setForeground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_entrar_txtMouseEntered

    private void entrar_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrar_txtMouseExited
        entrar_txt.setForeground(Color.white);
    }//GEN-LAST:event_entrar_txtMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastre;
    private javax.swing.JPanel entrar_botao;
    private javax.swing.JLabel entrar_txt;
    private javax.swing.JLabel entre;
    private javax.swing.JLabel fichaTecnica;
    private javax.swing.JLabel fichaTecnica1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel naoTemConta;
    private javax.swing.JPasswordField preencherSenha;
    private javax.swing.JTextField preencherUsuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables

    public JPasswordField getPreencherSenha() {
        return preencherSenha;
    }

    public void setPreencherSenha(JPasswordField preencherSenha) {
        this.preencherSenha = preencherSenha;
    }

    public JTextField getPreencherUsuario() {
        return preencherUsuario;
    }

    public void setPreencherUsuario(JTextField preencherUsuario) {
        this.preencherUsuario = preencherUsuario;
    }

}
