/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import FiveCodMover.FiveCodMoverJFrame;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;

/**
 *
 * @author vinic
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Menu() {
        initComponents();

        Inicio telaInicio = new Inicio();
        jDesktopPane1.add(telaInicio);
        telaInicio.setVisible(true);
        jLabel_inicio.setOpaque(true);
        jLabel_inicio.setBackground(new java.awt.Color(36, 46, 68));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel5_opcoes = new javax.swing.JPanel();
        jLabel_GerarFicha = new javax.swing.JLabel();
        jLabel_CopiarFicha = new javax.swing.JLabel();
        jLabel_AtualizarFicha = new javax.swing.JLabel();
        jLabel_CriarFicha = new javax.swing.JLabel();
        jLabel_ExcluirFicha = new javax.swing.JLabel();
        fichaTecnica1 = new javax.swing.JLabel();
        fichaTecnica = new javax.swing.JLabel();
        jLabel_inicio = new javax.swing.JLabel();
        jLabel_Sair = new javax.swing.JLabel();
        jPanel4_fundoAzul = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha Técnica");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel5_opcoes.setBackground(new java.awt.Color(89, 199, 198));
        JPanel5_opcoes.setPreferredSize(new java.awt.Dimension(300, 520));

        jLabel_GerarFicha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_GerarFicha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_GerarFicha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_GerarFicha.setText("Gerar Ficha");
        jLabel_GerarFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_GerarFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_GerarFichaMouseClicked(evt);
            }
        });

        jLabel_CopiarFicha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_CopiarFicha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CopiarFicha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CopiarFicha.setText("Copiar Ficha");
        jLabel_CopiarFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CopiarFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CopiarFichaMouseClicked(evt);
            }
        });

        jLabel_AtualizarFicha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_AtualizarFicha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AtualizarFicha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AtualizarFicha.setText("Atualizar Ficha");
        jLabel_AtualizarFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_AtualizarFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AtualizarFichaMouseClicked(evt);
            }
        });

        jLabel_CriarFicha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_CriarFicha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CriarFicha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CriarFicha.setText("Criar Ficha");
        jLabel_CriarFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CriarFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CriarFichaMouseClicked(evt);
            }
        });

        jLabel_ExcluirFicha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_ExcluirFicha.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ExcluirFicha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ExcluirFicha.setText("Excluir Ficha");
        jLabel_ExcluirFicha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ExcluirFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExcluirFichaMouseClicked(evt);
            }
        });

        fichaTecnica1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        fichaTecnica1.setForeground(new java.awt.Color(255, 255, 255));
        fichaTecnica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaTecnica1.setText("Ficha Técnica");

        fichaTecnica.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        fichaTecnica.setForeground(new java.awt.Color(255, 255, 255));
        fichaTecnica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fichaTecnica.setText("Gerador");

        jLabel_inicio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_inicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_inicio.setText("Inicio");
        jLabel_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_inicioMouseClicked(evt);
            }
        });

        jLabel_Sair.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_Sair.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Sair.setText("Sair");
        jLabel_Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanel5_opcoesLayout = new javax.swing.GroupLayout(JPanel5_opcoes);
        JPanel5_opcoes.setLayout(JPanel5_opcoesLayout);
        JPanel5_opcoesLayout.setHorizontalGroup(
            JPanel5_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel5_opcoesLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(fichaTecnica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel5_opcoesLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(fichaTecnica1)
                .addGap(28, 28, 28))
            .addComponent(jLabel_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_CriarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_AtualizarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_CopiarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_ExcluirFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_GerarFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPanel5_opcoesLayout.setVerticalGroup(
            JPanel5_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel5_opcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fichaTecnica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fichaTecnica)
                .addGap(76, 76, 76)
                .addComponent(jLabel_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CriarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AtualizarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CopiarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ExcluirFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_GerarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(JPanel5_opcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        jPanel4_fundoAzul.setBackground(new java.awt.Color(36, 46, 68));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4_fundoAzulLayout = new javax.swing.GroupLayout(jPanel4_fundoAzul);
        jPanel4_fundoAzul.setLayout(jPanel4_fundoAzulLayout);
        jPanel4_fundoAzulLayout.setHorizontalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel4_fundoAzulLayout.setVerticalGroup(
            jPanel4_fundoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        getContentPane().add(jPanel4_fundoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 640, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_inicioMouseClicked
        //Chama interface inicio dentro do menu
        jDesktopPane1.removeAll();
        Inicio telaInicio = new Inicio();
        jDesktopPane1.add(telaInicio);
        telaInicio.setVisible(true);

        //Volta a cor de fundo para azul claro
        jLabel_CriarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CopiarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_GerarFicha.setBackground(new java.awt.Color(89, 199, 198));

        //Mudar cor de fundo do botão
        jLabel_inicio.setOpaque(true);
        jLabel_inicio.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_inicioMouseClicked

    private void jLabel_CriarFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CriarFichaMouseClicked
        jDesktopPane1.removeAll();
        CriarFicha telaCriarFicha = new CriarFicha();
        jDesktopPane1.add(telaCriarFicha);
        telaCriarFicha.setVisible(true);

        jLabel_inicio.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CopiarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_GerarFicha.setBackground(new java.awt.Color(89, 199, 198));

        jLabel_CriarFicha.setOpaque(true);
        jLabel_CriarFicha.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_CriarFichaMouseClicked

    private void jLabel_AtualizarFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AtualizarFichaMouseClicked
        jDesktopPane1.removeAll();
        AtualizarFicha telaAtualizarFicha = new AtualizarFicha();
        jDesktopPane1.add(telaAtualizarFicha);
        telaAtualizarFicha.setVisible(true);

        jLabel_inicio.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CriarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CopiarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_GerarFicha.setBackground(new java.awt.Color(89, 199, 198));

        jLabel_AtualizarFicha.setOpaque(true);
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_AtualizarFichaMouseClicked

    private void jLabel_CopiarFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CopiarFichaMouseClicked
        jDesktopPane1.removeAll();
        CopiarFicha telaCopiarFicha = new CopiarFicha();
        jDesktopPane1.add(telaCopiarFicha);
        telaCopiarFicha.setVisible(true);

        jLabel_inicio.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CriarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_GerarFicha.setBackground(new java.awt.Color(89, 199, 198));

        jLabel_CopiarFicha.setOpaque(true);
        jLabel_CopiarFicha.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_CopiarFichaMouseClicked

    private void jLabel_ExcluirFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExcluirFichaMouseClicked
        jDesktopPane1.removeAll();
        ExcluirFicha telaExcluirFicha = new ExcluirFicha();
        jDesktopPane1.add(telaExcluirFicha);
        telaExcluirFicha.setVisible(true);

        jLabel_inicio.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CriarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CopiarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_GerarFicha.setBackground(new java.awt.Color(89, 199, 198));

        jLabel_ExcluirFicha.setOpaque(true);
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_ExcluirFichaMouseClicked

    private void jLabel_GerarFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GerarFichaMouseClicked
        jDesktopPane1.removeAll();
        GerarFicha telaGerarFicha = new GerarFicha();
        jDesktopPane1.add(telaGerarFicha);
        telaGerarFicha.setVisible(true);

        jLabel_inicio.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CriarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_AtualizarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_CopiarFicha.setBackground(new java.awt.Color(89, 199, 198));
        jLabel_ExcluirFicha.setBackground(new java.awt.Color(89, 199, 198));

        jLabel_GerarFicha.setOpaque(true);
        jLabel_GerarFicha.setBackground(new java.awt.Color(36, 46, 68));
    }//GEN-LAST:event_jLabel_GerarFichaMouseClicked

    private void jLabel_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SairMouseClicked
        dispose();
    }//GEN-LAST:event_jLabel_SairMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public JLabel getjLabel_inicio() {
        return jLabel_inicio;
    }

    public void setjLabel_inicio(JLabel jLabel_inicio) {
        this.jLabel_inicio = jLabel_inicio;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel5_opcoes;
    private javax.swing.JLabel fichaTecnica;
    private javax.swing.JLabel fichaTecnica1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel_AtualizarFicha;
    private javax.swing.JLabel jLabel_CopiarFicha;
    private javax.swing.JLabel jLabel_CriarFicha;
    private javax.swing.JLabel jLabel_ExcluirFicha;
    private javax.swing.JLabel jLabel_GerarFicha;
    private javax.swing.JLabel jLabel_Sair;
    private javax.swing.JLabel jLabel_inicio;
    private javax.swing.JPanel jPanel4_fundoAzul;
    // End of variables declaration//GEN-END:variables

}
